### ISSUE TITLE
End of subscription period

### ISSUE THREAD

**Issue by vvMalko** [SAIBA0011/laravel-billing#1]
Hello, help me understand please.
To create a subscription by `$user->subscription( 'myplan')->create()`;
The plan is targeted for a month.
On a Windows laptop while translating a couple of months in advance, and the subscription is not over, the method `auth()->user()->subscribed()` returns `TRUE`
How to verify that the subscription has ende

**Comment by SAIBA0011** [comment]
The Subscriptions run until a user or admin has cancelled their subscription with 

``` php
$user->subscription()->cancel();
```

I found that the billing is set to Cancelled if billing_active is set to false and billing_subscription_ends_at is in the past. To remove the plan from user the cancel_at field on subscriptions must be in the past as well.

Hope this helps.
I'm going to do a complete re-write based on this package with a similar api soon for laravel 5.1 and 5.2 that support more gateways as Stripe is not available in my country.

PS if you using stripe, you're better off using cashier.
